project:
  type: website

website:
  title: "What Defines Happiness?"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: graphs.qmd
        text: Graphs
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: lux
    css: styles.css
    toc: true
